FROM ruby:3.4.2

# Установка необходимых пакетов для разработки
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    postgresql-client \
    nodejs \
    npm

# Создание директории приложения
WORKDIR /rails

# Установка гемов
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Копируем entrypoint скрипт и делаем его исполнимым
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

# Настройка entrypoint
ENTRYPOINT ["entrypoint.sh"]

# Запуск Rails сервера по умолчанию
CMD ["rails", "server", "-b", "0.0.0.0"]
