services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: ruby_api_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ruby_api
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ".:/myapp"
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/myapp_development
      RAILS_ENV: development

volumes:
  postgres_data:
  bundle_cache:
